version: '3.8'

services:
  file-service:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      file-db:
        condition: service_healthy

  file-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - file_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  file_db_data:
